language: java
jdk:
  - openjdk11

jobs:
  include:
    - os: linux
#      env: BUILD_ARGS=--no-server
    - os: osx
#      env: BUILD_ARGS=--no-server
    - os: windows
      language: shell
#      env: BUILD_ARGS=
install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install windows-sdk-7.1 kb2519277 zip unzip; fi

before_script:
  - chmod +x mvnw
script:
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk list java
  - sdk install java 19.3.0.r11-grl
  - if [ $TRAVIS_OS_NAME != windows ]; then unset JAVA_HOME ; fi
  - java -version
  - ./mvnw --version; ./mvnw -DbuildArgs=${BUILD_ARGS} clean verify
  - if [ $TRAVIS_OS_NAME  = windows ]; then "$JAVA_HOME/bin/jar.exe" -cMvf target/checksum-$TRAVIS_OS_NAME.zip target/picocli-native-image-maven-demo.exe ; fi
  - if [ $TRAVIS_OS_NAME != windows ]; then zip -v target/picocli-native-image-maven-demo-$TRAVIS_OS_NAME.zip target/picocli-native-image-maven-demo ; fi

# Deploy the resulting artifact to GitHub Releases
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: build/graal/checksum-$TRAVIS_OS_NAME.zip
#  skip_cleanup: true
#  on:
#    tags: true

# avoid uploading the cache after every build
#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
